/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9P5JD7ifyiu
 */
import Link from "next/link"
import { usePathname } from "next/navigation";

let bottomNavs = [
  {
    label: "Home",
    href: "/",
    icon: <HomeIcon className="h-6 w-6" />
  },
  {
    label: "Categories",
    href: "/category",
    icon: <LayoutGridIcon className="h-6 w-6" />
  },
  {
    label: "New",
    href: "/new",
    icon: <PenToolIcon className="h-6 w-6" />
  },
  {
    label: "Cart",
    href: "/cart",
    icon: <ShoppingBagIcon className="h-6 w-6" />
  },
  {
    label: "Profile",
    href: "/me",
    icon: <UserIcon className="h-6 w-6" />
  }
]

export function BottomNav() {
  const pathname = usePathname()
  console.log(pathname)
  return (
    (<footer className="fixed inset-x-0 bottom-0 flex flex-1 flex-row " style={{
      margin: "0 auto",
      borderTop: "1px solid gray",
      backgroundColor: "white",
      maxWidth:"600px",
      width:"100%"
    }}>
      {bottomNavs.map((link) => {
        const isActive = pathname.startsWith(link.href)
        return (
          <Link
            className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
            style={{
              color: isActive? "black":"",
              fontWeight: isActive?"bold":""
            }}
            href={link.href}>
            {link.icon}
            {link.label}
          </Link>
        )
      })}

      {/* 
      <Link
        className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
        href="#">
        <HomeIcon className="h-6 w-6" />
        Home
      </Link>
      <Link
        className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
        href="#">
        <LayoutGridIcon className="h-6 w-6" />
        Categories
      </Link>
      <Link
        className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
        href="#">
        <PenToolIcon className="h-6 w-6" />
        New
      </Link>
      <Link
        className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
        href="#">
        <ShoppingBagIcon className="h-6 w-6" />
        Cart
      </Link>
      <Link
        className="flex flex-1 flex-col items-center justify-center py-2 text-sm text-gray-500 dark:text-gray-400"
        href="#">
        <UserIcon className="h-6 w-6" />
        Profile
      </Link>
     
     */}
    </footer>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LayoutGridIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>)
  );
}


function PenToolIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19 7-7 3 3-7 7-3-3z" />
      <path d="m18 13-1.5-7.5L2 2l3.5 14.5L13 18l5-5z" />
      <path d="m2 2 7.586 7.586" />
      <circle cx="11" cy="11" r="2" />
    </svg>)
  );
}


function ShoppingBagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
      <path d="M3 6h18" />
      <path d="M16 10a4 4 0 0 1-8 0" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
