/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WeazcayYZ3g
 */
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function Cart() {
  return (
    (<div className="bg-white max-w-[600px] mx-auto">
      <div className="flex items-center justify-between p-4 border-b">
        <ArrowLeftIcon className="text-black" />
        <h1 className="text-lg font-semibold">Cart</h1>
        <span className="text-sm">Ship to United States</span>
        <SettingsIcon className="text-black" />
      </div>
      <div className="flex flex-col items-center justify-center p-10">
        <ShoppingCartIcon className="text-gray-400 w-24 h-24" />
        <p className="mt-4 text-gray-600">Your cart is empty</p>
        <Button className="mt-6 w-full bg-black text-white">SIGN IN / REGISTER</Button>
        <Button
          className="mt-4 w-full bg-white text-black border border-gray-200 border-black dark:border-gray-800">SHOP NOW</Button>
      </div>
      <div className="px-4 py-2">
        <h2 className="text-lg font-semibold mb-4">You Might Like to Fill it With</h2>
        <div className="grid grid-cols-2 gap-4">
          <Card className="w-full">
            <img
              alt="4Pcs Tempered Glass"
              className="w-full"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "150/150",
                objectFit: "cover",
              }}
              width="150" />
            <div className="p-2">
              <p className="text-sm">4Pcs Tempered Glass...</p>
              <div className="flex items-center justify-between">
                <span className="text-yellow-500 text-sm">
                  {""}
                  $1.84 <span className="text-gray-500 line-through">-44%</span>
                </span>
                <Button className="bg-gray-200 p-1">+</Button>
              </div>
            </div>
          </Card>
          <Card className="w-full">
            <img
              alt="SHEIN Boys' Two-Piece Letter"
              className="w-full"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "150/150",
                objectFit: "cover",
              }}
              width="150" />
            <div className="p-2">
              <p className="text-sm">SHEIN Boys' Two-Piece Letter...</p>
              <div className="flex items-center justify-between">
                <span className="text-yellow-500 text-sm">
                  {""}
                  $6.80 <span className="text-gray-500 line-through">-35%</span>
                </span>
                <Button className="bg-gray-200 p-1">+</Button>
              </div>
              <div className="flex space-x-1 mt-2">
                <span className="block w-4 h-4 bg-gray-300 rounded-full" />
                <span className="block w-4 h-4 bg-red-500 rounded-full" />
                <span className="block w-4 h-4 bg-green-600 rounded-full" />
                <span className="block w-4 h-4 bg-yellow-600 rounded-full" />
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>)
  );
}


function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}
