/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q8G8A4zmc5f
 */
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"

export function HomeFront() {
  return (
    (<div key="1" className="bg-white">
      <div className="flex items-center justify-between p-4 border-b">
        <MenuIcon className="text-black" />
        <div className="flex items-center space-x-2">
          <SearchIcon className="text-black" />
          <Input className="border-0" placeholder="Skirt" type="text" />
        </div>
        <div className="flex items-center space-x-4">
          <CameraIcon className="text-black" />
          <HeartIcon className="text-black" />
          <ShoppingCartIcon className="text-black" />
        </div>
      </div>
      <div className="flex justify-around bg-gray-200 p-2 text-sm">
        <Link className="block" href="#">
          All
        </Link>
        <Link className="block" href="#">
          Women
        </Link>
        <Link className="block" href="#">
          Curve
        </Link>
        <Link className="block" href="#">
          Kids
        </Link>
        <Link className="block" href="#">
          Marketplace
        </Link>
        <Link className="block" href="#">
          Men
        </Link>
        <Link className="block" href="#">
          Home
        </Link>
      </div>
      <div className="flex justify-between bg-yellow-100 p-2 text-sm">
        <Link className="block text-red-600" href="#">
          Return Policy
        </Link>
        <span>Free returns within 35 days.</span>
      </div>
      <div className="grid grid-cols-2 gap-2 p-2">
        <Card className="w-full">
          <img
            alt="Golden Geometric Irregular Bracelet"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <div className="p-2">
            <p className="text-xs text-red-500">SPRING SALE</p>
            <p className="text-sm">1set Golden Geometric Irregular Bracelet</p>
            <p className="text-xs text-gray-500">5.1k+ sold recently</p>
            <p className="text-lg font-bold">
              $1.64
              <span className="text-sm line-through">$2.10</span>
            </p>
            <Badge variant="secondary">-22%</Badge>
          </div>
        </Card>
        <Card className="w-full">
          <img
            alt="SHEIN Unity Allover Print Bodycon Skirt"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <div className="p-2">
            <p className="text-xs text-yellow-500">FLASH SALE</p>
            <p className="text-sm">SHEIN Unity Allover Print Bodycon Skirt</p>
            <p className="text-xs text-gray-500">5.6k+ sold recently</p>
            <p className="text-lg font-bold">
              $9.95
              <span className="text-sm line-through">$17.19</span>
            </p>
            <Badge variant="secondary">-42%</Badge>
          </div>
        </Card>
        <Card className="w-full">
          <img
            alt="SHEIN Essence Off Shoulder Sweater"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <div className="p-2">
            <p className="text-xs text-red-500">SPRING SALE</p>
            <p className="text-sm">SHEIN Essence Off Shoulder Sweater</p>
            <p className="text-xs text-gray-500">10k+ sold recently</p>
            <p className="text-lg font-bold">
              $10.87
              <span className="text-sm line-through">$14.69</span>
            </p>
            <Badge variant="secondary">-26%</Badge>
          </div>
        </Card>
        <Card className="w-full">
          <img
            alt="Jaysuing Acne Patches"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <div className="p-2">
            <p className="text-xs text-green-500">#1 Best Sellers in Acne...</p>
            <p className="text-sm">Jaysuing acne patches-200...</p>
            <p className="text-xs text-gray-500">Best seller</p>
            <p className="text-lg font-bold">
              $2.10
              <span className="text-sm line-through">$2.21</span>
            </p>
            <Badge variant="secondary">-5%</Badge>
          </div>
        </Card>
      </div>
      <div
        className="fixed bottom-0 left-0 right-0 flex justify-around bg-white p-2 text-sm border-t">
        <HomeIcon className="text-black" />
        <LayoutGridIcon className="text-black" />
        <PlusCircleIcon className="text-black" />
        <ShoppingCartIcon className="text-black" />
        <UserIcon className="text-black" />
      </div>
    </div>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function CameraIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>)
  );
}


function HeartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LayoutGridIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>)
  );
}


function PlusCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 12h8" />
      <path d="M12 8v8" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
