'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kc4UYSxz1tk
 */
import { Button } from "@/components/ui/button"
import { RightOutline } from "antd-mobile-icons";
export function StoreCard() {
  return (
    (<div className="max-w-[500px]  p-2"
    
    style={{
      width:'100%'
    }}
    >
      <div className="flex items-center space-x-4"
      style={{
        padding:'10px 12.5px',
        paddingBottom:'16px'
      }}
      >
        <img
          alt="SHEIN ICON"
          className="h-10 w-10"
          height="50"
          src="/placeholder.svg"
          style={{
            aspectRatio: "80/80",
            objectFit: "cover",
          }}
          width="50" />
        <div className="flex-1">
          <h1 
          style={{
            fontSize:"14px"
          }}
          
          className=" font-bold">SHEIN ICON</h1>
          <p className="text-sm text-gray-500 truncate detail-title-text desc-new">SHEIN ICON ensures you never go unnoticed with...</p>
        </div>
        <RightOutline fontSize={17}/>
      </div>
      <div className="flex justify-between    px-3">
        <div className="text-center">
          <div className="text-[12px] font-semibold">4.87</div>
          <div className="text-[11px] text-gray-500">Rating</div>
        </div>
        <div className=" px-4">
          <div className="text-[12px] font-semibold">17K</div>
          <div className="text-[11px] text-gray-500">Items</div>
        </div>
        <div className="text-center">
          <div className="text-[12px] font-semibold">51K</div>
          <div className="text-[11px] text-gray-500">Followers</div>
        </div>
      </div>
      <div className="flex space-x-4 mt-4 mx-2">
        <Button className="flex-1" variant="outline">
          + Follow
        </Button>
        <Button className="flex-1" variant="outline">
          All Items
        </Button>
      </div>
    </div>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
